name: CLFeatures
main: de.craftlancer.clfeatures.CLFeatures
api-version: 1.14
author: Syd Montague
version: ${project.version}
depend: [CLCore]
commands:
  portal:
    description: "Portal related commands"
    usage: /portal [list|name|move]
  stonecrusher:
    description: "Stonecrusher related commands"
    usage: /stonecrusher [move]
permissions:
  clfeature.portal.ignoreLimit:
    default: op